version: "3"
services:
  redis: 
   image: redis

  db:
   image: postgres:15-alpine

  web-vote-app:
   image: voting-app-frontend
   depends_on:
    - redis
   ports:
     - 8000:80
   links:
     - "redis"

  worker-app:
   image: worker-app
   links:
     - "redis"
     - "db"

  result-app:
   image: result-app
   ports:
     - 8001:80
   links:
     - "db"            


